# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cffda3f50f53a8174018a68f40b8897a7f4812ecad8cf21f638c82a354e3c5fe9cd5dea1c3c6392ec20761dcb9a2bfda821da7f466c34872ba36426c9a906c69

test:
  secret_key_base: 1c6d738acab8d0be243f7aa1130431bfacb41001a7ff05a9c4bb93f72b9a0efff22b7a672fb2ffbda1c48425ff62d5cf01158a6bab802c5f1216bf6e6863e491

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
